### ISSUE TITLE
It doesn't seem to work

### ISSUE THREAD

**Issue by samhed** [bernikr/lovelace-webos-keyboard#1]
Do I need to setup something other than what's written in the README?

I have the LG web OS integration and my TV appears as a media_player entity which works well.

I added this custom card and set it up to use my TV media_player, but nothing happens when I type in the input field.

**Comment by bernikr** [comment]
The setup in the readme should be sufficent. Unfortuanatly due to the limitations of the TV it only works to type into fields where the stock keyboard on the tv opens. If the app you are using proviedes its own keyboard (e.g. Youtube or Plex) the keypresses are ignored.

That behaviour unfortunatly seemes to be due to the way webos and the apps work and there seems to be no way around it.

**Comment by samhed** [comment]
I forgot to respond here. You're right, it does work if I use the LG Content Store search, it doesn't work in Netflix or YouTube.
